Repository TIHLDE/Codex, pull requests merged in 2024-11, with the labels that each got.

#55 Created docs for creating a psql db for a project
  src/app/(private)/(docs)/docs/drift/databaser/create-postgresql-database/page.md
  src/lib/navigation.ts
Labels: doc

#61 Make the 404 page be Norwegian instead of English
  src/app/not-found.tsx
Labels: refactor

#64 FIX: Code fences exception when not providing language
  src/app/(private)/(docs)/docs/drift/linux/users/page.md
  src/app/(private)/(docs)/docs/lepton/external_api/feide/page.md
  src/markdoc/nodes.js
Labels: bug

#65 REFACTOR: Change default mono font to JetbrainsMono
  src/app/layout.tsx
  tailwind.config.ts
Labels: refactor

#67 fixed bad docs
  src/app/(private)/(docs)/docs/drift/databaser/create-postgresql-database/page.md
Labels: doc

#69 Implement quiz component
  README.md
  src/app/(private)/(docs)/page.md
  src/components/documentation/Quiz.tsx
  src/markdoc/tags.js
Labels: new feature
